-- 1. Define the Types
INSERT INTO Types (Type, Kind)
VALUES  ('CIVILIZATION_BRAINROT_DSH', 'KIND_CIVILIZATION'),
        ('TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY', 'KIND_TRAIT'),
        ('LEADER_TRIPLE_T_DSH', 'KIND_LEADER'),
        ('TRAIT_LEADER_TRIPLE_T_DSH_ABILITY', 'KIND_TRAIT');

-- 2. Define the Civilization
INSERT INTO Civilizations (CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity)
VALUES  ('CIVILIZATION_BRAINROT_DSH', 'LOC_CIVILIZATION_BRAINROT_DSH_NAME', 'LOC_CIVILIZATION_BRAINROT_DSH_DESCRIPTION', 'LOC_CIVILIZATION_BRAINROT_DSH_ADJECTIVE', 'CIVILIZATION_LEVEL_FULL_CIV', 10, 'ETHNICITY_EURO');

-- 3. Define the Leader
INSERT INTO Leaders (LeaderType, Name, InheritFrom, SceneLayers)
VALUES  ('LEADER_TRIPLE_T_DSH', 'LOC_LEADER_TRIPLE_T_DSH_NAME', 'LEADER_DEFAULT', 4);

-- 4. Link Leader to Civilization
INSERT INTO CivilizationLeaders (CivilizationType, LeaderType, CapitalName)
VALUES  ('CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'LOC_CITY_NAME_BRAINROT_DSH_CAPITAL');

-- 5. Give the Civilization City Names (You need at least a capital)
INSERT INTO CityNames (CivilizationType, CityName)
VALUES  ('CIVILIZATION_BRAINROT_DSH', 'LOC_CITY_NAME_BRAINROT_DSH_CAPITAL'),
        ('CIVILIZATION_BRAINROT_DSH', 'LOC_CITY_NAME_BRAINROT_DSH_SECOND_CITY');

-- 6. Define Traits (Abilities)
INSERT INTO Traits (TraitType, Name, Description)
VALUES  ('TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_NAME', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_DESCRIPTION'),
        ('TRAIT_LEADER_TRIPLE_T_DSH_ABILITY', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_NAME', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_DESCRIPTION');

-- 7. Link Traits to Civ and Leader
INSERT INTO CivilizationTraits (CivilizationType, TraitType)
VALUES  ('CIVILIZATION_BRAINROT_DSH', 'TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY');

INSERT INTO LeaderTraits (LeaderType, TraitType)
VALUES  ('LEADER_TRIPLE_T_DSH', 'TRAIT_LEADER_TRIPLE_T_DSH_ABILITY');

-- 8. In-Game Player Colors
INSERT INTO PlayerColors (Type, Usage, PrimaryColor, SecondaryColor, TextColor)
VALUES  ('LEADER_TRIPLE_T_DSH', 'Unique', 'COLOR_PLAYER_WHITE_TEXT', 'COLOR_PLAYER_Transparent_Background', 'COLOR_PLAYER_WHITE_TEXT');

-- 9. AI Agenda and Quotes
INSERT INTO HistoricalAgendas (LeaderType, AgendaType)
VALUES  ('LEADER_TRIPLE_T_DSH', 'AGENDA_PARANOID');

INSERT INTO LeaderQuotes (LeaderType, Quote)
VALUES  ('LEADER_TRIPLE_T_DSH', 'LOC_PEDIA_LEADERS_PAGE_LEADER_TRIPLE_T_DSH_QUOTE');