-- 1. Define the Player Color for the Setup Screen

-- 2. Define the Civ and Leader for ALL Rulesets (The Brute Force Method)
INSERT INTO Players (Domain, CivilizationType, Portrait, CivilizationName, CivilizationIcon, CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderType, LeaderName, LeaderIcon, LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon)
VALUES  
('Players:StandardPlayers', 'CIVILIZATION_BRAINROT_DSH',"LEADER_TRIPLE_T_NEUTRAL", 'LOC_CIVILIZATION_BRAINROT_DSH_NAME', 'ICON_CIVILIZATION_BRAINROT_DSH', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_NAME', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_DESCRIPTION', 'ICON_CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'LOC_LEADER_TRIPLE_T_DSH_NAME', 'ICON_LEADER_TRIPLE_T_DSH', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_NAME', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_DESCRIPTION', 'ICON_LEADER_TRIPLE_T_DSH'),
('Players:Expansion1_Players', 'CIVILIZATION_BRAINROT_DSH',"LEADER_TRIPLE_T_NEUTRAL", 'LOC_CIVILIZATION_BRAINROT_DSH_NAME', 'ICON_CIVILIZATION_BRAINROT_DSH', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_NAME', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_DESCRIPTION', 'ICON_CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'LOC_LEADER_TRIPLE_T_DSH_NAME', 'ICON_LEADER_TRIPLE_T_DSH', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_NAME', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_DESCRIPTION', 'ICON_LEADER_TRIPLE_T_DSH'),
('Players:Expansion2_Players', 'CIVILIZATION_BRAINROT_DSH',"LEADER_TRIPLE_T_NEUTRAL", 'LOC_CIVILIZATION_BRAINROT_DSH_NAME', 'ICON_CIVILIZATION_BRAINROT_DSH', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_NAME', 'LOC_TRAIT_CIVILIZATION_BRAINROT_DSH_ABILITY_DESCRIPTION', 'ICON_CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'LOC_LEADER_TRIPLE_T_DSH_NAME', 'ICON_LEADER_TRIPLE_T_DSH', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_NAME', 'LOC_TRAIT_LEADER_TRIPLE_T_DSH_ABILITY_DESCRIPTION', 'ICON_LEADER_TRIPLE_T_DSH');

-- 3. Link UI items for ALL Rulesets
INSERT INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex)
VALUES  
('Players:StandardPlayers', 'CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'UNIT_SWORDSMAN', 'ICON_UNIT_SWORDSMAN', 'LOC_UNIT_SWORDSMAN_NAME', 'LOC_UNIT_SWORDSMAN_DESCRIPTION', 10),
('Players:StandardPlayers', 'CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'BUILDING_MONUMENT', 'ICON_BUILDING_MONUMENT', 'LOC_BUILDING_MONUMENT_NAME', 'LOC_BUILDING_MONUMENT_DESCRIPTION', 20),
('Players:Expansion1_Players', 'CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'UNIT_SWORDSMAN', 'ICON_UNIT_SWORDSMAN', 'LOC_UNIT_SWORDSMAN_NAME', 'LOC_UNIT_SWORDSMAN_DESCRIPTION', 10),
('Players:Expansion1_Players', 'CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'BUILDING_MONUMENT', 'ICON_BUILDING_MONUMENT', 'LOC_BUILDING_MONUMENT_NAME', 'LOC_BUILDING_MONUMENT_DESCRIPTION', 20),
('Players:Expansion2_Players', 'CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'UNIT_SWORDSMAN', 'ICON_UNIT_SWORDSMAN', 'LOC_UNIT_SWORDSMAN_NAME', 'LOC_UNIT_SWORDSMAN_DESCRIPTION', 10),
('Players:Expansion2_Players', 'CIVILIZATION_BRAINROT_DSH', 'LEADER_TRIPLE_T_DSH', 'BUILDING_MONUMENT', 'ICON_BUILDING_MONUMENT', 'LOC_BUILDING_MONUMENT_NAME', 'LOC_BUILDING_MONUMENT_DESCRIPTION', 20);